# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 浩然瞎比比
subtitle: Make more time 
description: 
author: anhr
language: zh-CN
timezone:
scheme: Litten
#baidu_tongji: true ## 百度统计

# Miscellaneous
#baidu_analytics: 'ae3afa2b5fa3eee5fcdf23fb6c85154e'
#google_analytics: 'UA-9700xxxxxxxx'
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://anhr.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 4
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: BlueLake
#theme: next
#smackdown 炫酷考拉
#aloha 
#next 简洁主题
#landscape 默认主题

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:anHaoRan/anHaoRan.github.io.git
  # repo: git@git.coding.net:anhr/anhr.git
  branch: master
  
jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
leancloud_visitors:
  enable: true
  app_id: 2vD6a9Nphb4AqPzPeKQHKJLF-gzGzoHsz
  app_key: fN9yW1El0tBmTBDATHkaQT7v
post:
  posted: 发表于
  visitors: 阅读次数